package com.fixzone.fixzon_backend;

import com.fixzone.fixzon_backend.config.StripeConfig;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import io.github.cdimascio.dotenv.Dotenv;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.boot.CommandLineRunner;

@SpringBootApplication
@EnableConfigurationProperties(StripeConfig.class)
public class FixzonBackendApplication {

    public static void main(String[] args) {
        Dotenv dotenv = Dotenv.configure().ignoreIfMissing().load();
        dotenv.entries().forEach(entry -> System.setProperty(entry.getKey(), entry.getValue()));
        SpringApplication.run(FixzonBackendApplication.class, args);
    }

    @Bean
    public CommandLineRunner initPaymentTable(org.springframework.jdbc.core.JdbcTemplate jdbcTemplate) {
        return args -> {
            jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS payments (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "booking_id BIGINT, " +
                "service_package_id UUID, " +
                "vehicle_id UUID, " +
                "date VARCHAR(255), " +
                "time_slot VARCHAR(255), " +
                "stripe_session_id VARCHAR(255), " +
                "amount DOUBLE PRECISION NOT NULL, " +
                "status VARCHAR(50) NOT NULL, " +
                "created_at TIMESTAMP" +
            ")");
            System.out.println("Payments table verified/created successfully!");
        };
    }
}
