package com.fixzone.fixzon_backend;

import com.fixzone.fixzon_backend.config.StripeConfig;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import io.github.cdimascio.dotenv.Dotenv;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.boot.CommandLineRunner;
import org.springframework.scheduling.annotation.EnableScheduling;

@SpringBootApplication
@EnableScheduling
@EnableConfigurationProperties(StripeConfig.class)
public class FixzonBackendApplication {
    private static final Logger log = LoggerFactory.getLogger(FixzonBackendApplication.class);

    public static void main(String[] args) {
        Dotenv dotenv = Dotenv.configure().ignoreIfMissing().load();
        dotenv.entries().forEach(entry -> System.setProperty(entry.getKey(), entry.getValue()));
        SpringApplication.run(FixzonBackendApplication.class, args);
    }

    @Bean
    public CommandLineRunner initPaymentTable(org.springframework.jdbc.core.JdbcTemplate jdbcTemplate) {
        return args -> {
            jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS payments (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "booking_id BIGINT, " +
                "service_package_id UUID, " +
                "vehicle_id UUID, " +
                "date VARCHAR(255), " +
                "time_slot VARCHAR(255), " +
                "stripe_session_id VARCHAR(255), " +
                "amount DOUBLE PRECISION NOT NULL, " +
                "status VARCHAR(50) NOT NULL, " +
                "created_at TIMESTAMP" +
            ")");
            log.info("Payments table verified/created successfully!");

            try {
                jdbcTemplate.execute("ALTER TABLE service_centers ALTER COLUMN business_reg_url TYPE TEXT;");
                jdbcTemplate.execute("ALTER TABLE service_centers ALTER COLUMN tax_id_url TYPE TEXT;");
                jdbcTemplate.execute("ALTER TABLE service_centers ALTER COLUMN nic_url TYPE TEXT;");
                log.info("service_centers columns successfully altered to TEXT!");
            } catch (Exception e) {
                log.warn("Could not alter service_centers columns to TEXT (may already be TEXT): " + e.getMessage());
            }
        };
    }
}
