server:
  port: 8081


spring:
  application:
    name: fixzon-backend
  datasource:
    url: jdbc:postgresql://ep-holy-thunder-aictgfer-pooler.c-4.us-east-1.aws.neon.tech/fixzone_db?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_NH7GqJS2ksgc
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
