server:
  port: 8081

spring:
  application:
    name: fixzon-backend
  datasource:
    url: jdbc:postgresql://ep-billowing-king-a1ez4i2v.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_jX9VpsAHb8zE
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
